[env:seeed_xiao_esp32s3]
platform = espressif32@6.9.0
board = seeed_xiao_esp32s3
framework = arduino
monitor_speed = 115200

lib_deps =
    adafruit/Adafruit NeoPixel @ ^1.12.3

board_build.filesystem = littlefs
upload_speed = 921600
